### PR TITLE
Fold Rstudio style section markers

### PR DESCRIPTION
**Pull request by jongbinjung**
Comments that end with four or more -, =, # are considered section
markers as in Rstudio.

### CODE REVIEW

**Comment by jalvesaq** [comment]
It looks like a good folding method, but I do not use folding, and I never was an RStudio user. So, it would be good if someone else commented on this. If nobody complains, I will merge it.

**Comment by jongbinjung** [comment]
Any update on this?

**Comment by jalvesaq** [comment]
Why did you change the highlighting rules for `BUG`, `TODO`, `FIXME` and `NOTE`?
Since we are talking about section headers, I think we should have `matchgroup=Title`.
What does `ms=s-2,me=s-1` mean?
[RStudio support](https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections) defines section headers as comment lines that end with 4 or more `[-=#]`. So, the pattern should be something like  `/^#.*[-=#]\{4,}$/`.

So, I tested the following:

```vim
  syn region rSection matchgroup=Title start=/^#.*[-=#]\{4,}$/ end=/^#.*[-=#]\{4,}$/ transparent contains=ALL fold
```

But the following code was not properly folded:
```r
a <- 1
b <- 2
if(a > b){
    d <- 4
    e <- 5
}

# This is section 1 ------

f <- 6
g <- 7

# This is section 2 ####

h <- 8
i <- 9

# This section 3 =======

j <- 10
l <- 11
```

**Comment by jalvesaq** [comment]
I have looked at you justification about `TODO` lines. Do you a link for the mentioned specification?

**Comment by jongbinjung** [comment]
The TODO is from Google's R style guide (https://google.github.io/styleguide/Rguide.xml#todo), which has been adapted at my workplace.

**Comment by jongbinjung** [comment]
From `:h syn-pattern`:

```
...
The offset takes the form of "{what}={offset}"
The {what} can be one of seven strings:

ms	Match Start	offset for the start of the matched text
me	Match End	offset for the end of the matched text
...
The {offset} can be:

s	start of the matched pattern
s+{nr}	start of the matched pattern plus {nr} chars to the right
s-{nr}	start of the matched pattern plus {nr} chars to the left
...
```

From the test example above, without the `ms`, `me`, the first `start` will match

```vim
# This is section 1 ------
```

and the _first_ end will match

```vim
# This is section 2 ####
```

and the _second_ start will actually match

```vim
# This section 3 =======
```

The `ms` `me` makes sure that each `end` match doesn't interfere with the next `start` match by offsetting the `end` match into some imaginary space to the left. To our benefit, the offsetting doesn't cross lines.

Taking your recommendations into account, the below seems to work fine, and I'll make changes reflecting this to the PR.
```vim
syn region rSection matchgroup=Title start=/^#.*[-=#]\{4,}/ end=/^#.*[-=#]\{4,}/ms=s-2,me=s-1 transparent contains=ALL fold
```

**Comment by jalvesaq** [comment]
You new `rSection` works as expected.
Regarding the Google's style TODO, there is no space and the username is between parenthesis. So, what about this:
```vim
syn match rTodoParen contained "\(BUG\|FIXME\|NOTE\|TODO\)\s*(.\{-})\s*:" contains=rTodoKeyw,rTodoInfo transparent
syn keyword rTodoKeyw BUG FIXME NOTE TODO contained
syn match rTodoInfo "(\zs.\{-}\ze)" contained
hi def link rTodoParen Comment
hi def link rTodoKeyw Todo
hi def link rTodoInfo SpecialComment
```

**Comment by jalvesaq** [comment]
I added `\s*` around the parenthesis because some people will put spaces and others will not. In French, for example, there is a space before some punctuation marks.

**Comment by jalvesaq** [comment]
I forgot... This line is changed:
```vim
syn match rComment contains=@Spell,rCommentTodo,rTodoParen,rOBlock "#.*"
```

**Comment by jongbinjung** [comment]
That seems to work well :)

**Comment by jalvesaq** [comment]
Thanks for your contribution!

**Pull request merged**
